
image: docker:23.0

services:
  - name: docker:23.0-dind
    alias: docker

stages:
  - build

# =============================================================================

build_tagged:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG =~ /v?(\d+\.)?(\d+\.)?(\*|\d+)(\+.*?)?$/

  tags:
    - "gitlab-org-docker"

  before_script:
    - export BUILD_TAG="$(echo ${CI_COMMIT_TAG} | tr '+' '-')"
    - export BUILD1_NAME="${DOCKERHUB_REGISTRY}/${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME//docker-}"

  script:
    - |
      echo "BUILD_TAG=${BUILD_TAG}"
      echo "BUILD1_NAME=${BUILD1_NAME}"
      echo "COMMIT_REF=${COMMIT_REF}"
      echo "COMMIT_HASH=${COMMIT_HASH}"
      echo "COMMIT_TAG=${CI_COMMIT_TAG}"

      docker build \
        --pull \
        --label "commit=${COMMIT_HASH}" \
        --tag "${BUILD1_NAME}:${BUILD_TAG}" \
        --tag "${BUILD1_NAME}:latest" \
        --build-arg COMMIT_REF=${COMMIT_REF} \
        --build-arg COMMIT_HASH=${COMMIT_HASH} .
      
      echo "${DOCKERHUB_PASSWORD}" | docker login --password-stdin -u "${DOCKERHUB_USERNAME}" "${DOCKERHUB_REGISTRY}"
      docker push "${BUILD1_NAME}:${BUILD_TAG}"
      docker push "${BUILD1_NAME}:latest"
      docker logout
